const baseQueryKey = {
  JOB_LIST: ["JOB", "LIST"],
  ALL_JOBS: ["JOBS"],
  JOB_DETAILS: ["JOB", "DETAILS"],
  CUSTOMER_LIST: ["CUSTOMER", "LIST"],
  ACCOUNT_LIST: ["ACCOUNT", "LIST"],
  JOB_METRICS: ["JOB", "METRICS"],
  TASK_LIST: ["TASK", "LIST"],
  TASK_DETAILS: ["TASK", "DETAILS"],
  URGENT_TASK_LIST: ["URGENT_TASK", "LIST"],
  CUSTOMER_DETAILS: ["CUSTOMER", "DETAILS"],
};

export default baseQueryKey;
